
<article class="product"><a href="/fullview/" class="product__link">
    <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
    <h2 class="product__title">Women Trousers</h2></a>
  <del class="product__price product__price_old">€ 79.00</del>
  <p class="product__price product__price_new">€ 59.00</p>
  <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
</article>