<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>VAIMO</title>
    <script src="js/modernizr.js"></script>
    <link rel="stylesheet" href="css/styles.css"/>
  </head>
  <body>
    <div class="stripe">
      <div class="stripe__wrapper">
        <section class="language">Swedish</section>
        <nav class="social"><a href="#" class="social__link social__link_tw"></a><a href="#" class="social__link social__link_fb"></a><a href="#" class="social__link social__link_in"></a></nav>
      </div>
    </div>
    <header class="header"><a href="/" class="logotype__link">
        <h1 class="logotype">Demostore: nifty brand slogan goes here</h1></a>
      <div class="card">
        <p class="card__summary">Cart 3 Items €75.00</p>
        <button type="button" class="card__checkout">Checkout</button>
        <div class="card__list">
          <div class="card__items">
                  <div class="item"><a href="#" class="item__link"><img src="images/photo.jpg" alt="Item photo" class="item__photo"/>
                      <div class="item__details"> 
                        <h3 class="item__title">Product Name</h3>
                        <p class="item__summary"> 1x € 25.00
                        </p>
                      </div></a>
                    <button type="button" class="item__remove"></button>
                  </div>
                  <div class="item"><a href="#" class="item__link"><img src="images/photo.jpg" alt="Item photo" class="item__photo"/>
                      <div class="item__details"> 
                        <h3 class="item__title">Product Name</h3>
                        <p class="item__summary"> 1x € 50.00
                        </p>
                      </div></a>
                    <button type="button" class="item__remove"></button>
                  </div>
          </div>
          <button type="button" class="card__checkout card__checkout_list">Go To Checkout</button>
        </div>
      </div>
      <form action="/search/" method="post" class="search">
        <input type="text" value="" placeholder="Search" name="keyword" required="required" class="search__keyword"/>
        <div class="search__category">Products</div>
      </form>
      <nav class="navigation"><a href="#" class="navigation__link">Women</a><a href="#" class="navigation__link">Men</a><a href="#" class="navigation__link">Junior</a><a href="#" class="navigation__link">Accessories</a>
        <div class="navigation__dropdown"> 
          <div class="navigation__label">Collections</div>
          <div class="navigation__container">
            <div class="navigation__title">Year</div>
            <div class="navigation__dropdown"> 
              <div class="navigation__label">2014</div>
              <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
            </div>
            <div class="navigation__dropdown"> 
              <div class="navigation__label">2013</div>
              <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
            </div>
            <div class="navigation__dropdown"> 
              <div class="navigation__label">2012</div>
              <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
            </div>
            <div class="navigation__dropdown"> 
              <div class="navigation__label">2011</div>
              <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a>
                <div class="navigation__dropdown"> 
                  <div class="navigation__label">Winter</div>
                  <div class="navigation__container"><a href="#" class="navigation__link">First Half</a><a href="#" class="navigation__link">Second Half</a></div>
                </div><a href="#" class="navigation__link">Spring</a>
              </div>
            </div><a href="#" class="navigation__link">Link</a><a href="#" class="navigation__link">Other Link</a>
          </div>
        </div><a href="#" class="navigation__link navigation__link_marked">Sale</a><a href="#" class="navigation__link navigation__link_right">My account</a>
      </nav>
    </header>
    <div class="scroller">
      <div class="scroller__wrapper">
        <div class="scroller__wrapper-inner"><a href="#" class="scroller__slide"><img src="images/slide-1.jpg" alt="Slide" class="scroller__photo"/></a><a href="#" class="scroller__slide"><img src="images/slide-2.jpg" alt="Slide" class="scroller__photo"/></a><a href="#" class="scroller__slide"><img src="images/slide-3.jpg" alt="Slide" class="scroller__photo"/></a><a href="#" class="scroller__slide"><img src="images/slide-4.jpg" alt="Slide" class="scroller__photo"/></a></div>
      </div>
      <menu type="toolbar" class="scroller__menu">
        <button type="button" class="scroller__prev"></button>
        <button type="button" class="scroller__next"></button>
      </menu>
      <menu type="toolbar" class="scroller__paginator"></menu>
    </div>
    <div class="favorite">
      <h1 class="favorite__title"><span>Our Favourites</span></h1>
      <menu type="toolbar" class="favorite__menu">
        <button type="button" class="favorite__button favorite__button_prev"></button>
        <button type="button" class="favorite__button favorite__button_next"></button>
      </menu>
      <div class="favorite__wrapper-outer">
        <div class="favorite__wrapper-inner">
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Winter Sweatshirt</h2></a>
            <p class="product__price">€ 79.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Women Trousers</h2></a>
            <del class="product__price product__price_old">€ 79.00</del>
            <p class="product__price product__price_new">€ 59.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Winter Sweatshirt</h2></a>
            <p class="product__price">€ 79.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Women Trousers</h2></a>
            <del class="product__price product__price_old">€ 79.00</del>
            <p class="product__price product__price_new">€ 59.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Winter Sweatshirt</h2></a>
            <p class="product__price">€ 79.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Women Trousers</h2></a>
            <del class="product__price product__price_old">€ 79.00</del>
            <p class="product__price product__price_new">€ 59.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Winter Sweatshirt</h2></a>
            <p class="product__price">€ 79.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Women Trousers</h2></a>
            <del class="product__price product__price_old">€ 79.00</del>
            <p class="product__price product__price_new">€ 59.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Winter Sweatshirt</h2></a>
            <p class="product__price">€ 79.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Women Trousers</h2></a>
            <del class="product__price product__price_old">€ 79.00</del>
            <p class="product__price product__price_new">€ 59.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Winter Sweatshirt</h2></a>
            <p class="product__price">€ 79.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
          <article class="product"><a href="/fullview/" class="product__link">
              <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
              <h2 class="product__title">Women Trousers</h2></a>
            <del class="product__price product__price_old">€ 79.00</del>
            <p class="product__price product__price_new">€ 59.00</p>
            <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
          </article>
        </div>
      </div>
    </div>
    <div data-url="http://frontend-test.vaimo.com/anton.nemtsev/public/tab/tabcontent/" class="tabs"></div>
    <article class="abstract">
      <h2 class="abstract__title"><span>This is our new store</span></h2>
      <div class="abstract__text">
        <p>Curabitur est justo, tincidunt sit amet dignissim suscipit, sodales at odio. Sed hendrerit elit malesuada tristique fermentum. Nam sed ultricies leo, ac fermentum nisi. Etiam quis dolor vel arcu scelerisque eleifend. Donec placerat aliquam lacus, quis vulputate urna lobortis in. Sed eu nisi eu arcu adipiscing laoreet. Sed pharetra urna vel purus aliquet hendrerit. Duis vel velit vitae odio tempus ultricies. Praesent ullamcorper bibendum elit, sollicitudin pulvinar risus consequat ac. Donec a porttitor nibh, ac pretium velit. Quisque quis leo venenatis, aliquet urna sed, gravida dui. Sed imperdiet aliquam dolor quis dignissim.</p>
        <p>Mauris ornare venenatis magna, vel commodo velit vestibulum ac. Praesent iaculis, neque vel ultricies posuere, enim risus posuere nisl, a rhoncus massa lorem sit amet tortor. Cras molestie turpis quis sem elementum, in ultricies ante iaculis. Morbi blandit tempor varius. Nullam vel adipiscing mauris. Suspendisse ante tortor, gravida id risus consectetur, cursus aliquam nibh. Nullam vulputate, nibh vitae vehicula viverra, lorem quam tincidunt justo, ut consectetur metus turpis sed ante. Praesent nec faucibus augue, at ornare elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus venenatis, orci sit amet viverra sagittis, nisi lacus ullamcorper ante, vitae viverra magna ligula et sem.</p>
      </div>
    </article>
    <footer class="footer">
      <div class="footer__wrapper">
        <section class="footer__column">
          <h2 class="footer__title">Top Categories</h2>
          <nav class="footer__navigation"><a href="#" class="footer__link">Women</a><a href="#" class="footer__link">Men</a><a href="#" class="footer__link">Junior</a><a href="#" class="footer__link">Accessories</a></nav>
        </section>
        <section class="footer__column">
          <h2 class="footer__title">Customer Service</h2>
          <nav class="footer__navigation"><a href="#" class="footer__link">Women</a><a href="#" class="footer__link">Men</a><a href="#" class="footer__link">Junior</a><a href="#" class="footer__link">Accessories</a></nav>
        </section>
        <section class="footer__column">
          <h2 class="footer__title">Newsletter Subscribe</h2>
          <form action="http://frontend-test.vaimo.com/anton.nemtsev/public/newsletter/subscribe/" method="post" class="subscribe">
            <fieldset class="subscribe__fieldset">
              <input type="email" name="email" placeholder="firstname.lastname@vaimo.com" value="" required="required" class="subscribe__email"/>
              <button type="submit" class="subscribe__submit">Subscribe</button>
            </fieldset>
            <p class="subscribe__state subscribe__state_in-progress"> <span class="subscribe__spinner"></span>Subscribeing to newsletter...</p>
            <p class="subscribe__state subscribe__state_success">Subscription successful.</p>
            <p class="subscribe__state subscribe__state_fail">Email verification failed...</p>
          </form>
        </section>
      </div>
    </footer>
    <script src="js/classList.js/classList.min.js"></script>
    <script src="js/promise-polyfill/Promise.min.js"></script>
    <script src="js/es5-shim/es5-shim.min.js"></script>
    <script src="js/es5-shim/es5-sham.min.js"></script>
    <script src="js/scripts.js" async="async" defer="defer"></script>
  </body>
</html>