
<header class="header"><a href="/" class="logotype__link">
    <h1 class="logotype">Demostore: nifty brand slogan goes here</h1></a>
  <div class="card">
    <p class="card__summary">Cart 3 Items €75.00</p>
    <button type="button" class="card__checkout">Checkout</button>
    <div class="card__list">
      <div class="card__items">
          <div class="item"><a href="#" class="item__link"><img src="images/photo.jpg" alt="Item photo" class="item__photo"/>
              <div class="item__details"> 
                <h3 class="item__title">Product Name</h3>
                <p class="item__summary"> 1x € 25.00
                </p>
              </div></a>
            <button type="button" class="item__remove"></button>
          </div>
          <div class="item"><a href="#" class="item__link"><img src="images/photo.jpg" alt="Item photo" class="item__photo"/>
              <div class="item__details"> 
                <h3 class="item__title">Product Name</h3>
                <p class="item__summary"> 1x € 50.00
                </p>
              </div></a>
            <button type="button" class="item__remove"></button>
          </div>
      </div>
      <button type="button" class="card__checkout card__checkout_list">Go To Checkout</button>
    </div>
  </div>
  <form action="/search/" method="post" class="search">
    <input type="text" value="" placeholder="Search" name="keyword" required="required" class="search__keyword"/>
    <div class="search__category">Products</div>
  </form>
  <nav class="navigation"><a href="#" class="navigation__link">Women</a><a href="#" class="navigation__link">Men</a><a href="#" class="navigation__link">Junior</a><a href="#" class="navigation__link">Accessories</a>
    <div class="navigation__dropdown"> 
      <div class="navigation__label">Collections</div>
      <div class="navigation__container">
        <div class="navigation__title">Year</div>
        <div class="navigation__dropdown"> 
          <div class="navigation__label">2014</div>
          <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
        </div>
        <div class="navigation__dropdown"> 
          <div class="navigation__label">2013</div>
          <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
        </div>
        <div class="navigation__dropdown"> 
          <div class="navigation__label">2012</div>
          <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
        </div>
        <div class="navigation__dropdown"> 
          <div class="navigation__label">2011</div>
          <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a>
            <div class="navigation__dropdown"> 
              <div class="navigation__label">Winter</div>
              <div class="navigation__container"><a href="#" class="navigation__link">First Half</a><a href="#" class="navigation__link">Second Half</a></div>
            </div><a href="#" class="navigation__link">Spring</a>
          </div>
        </div><a href="#" class="navigation__link">Link</a><a href="#" class="navigation__link">Other Link</a>
      </div>
    </div><a href="#" class="navigation__link navigation__link_marked">Sale</a><a href="#" class="navigation__link navigation__link_right">My account</a>
  </nav>
</header>