<form action="http://frontend-test.vaimo.com/anton.nemtsev2/public/newsletter/subscribe/" method="post" class="subscribe">
    <fieldset class="subscribe__fieldset">
        <input type="email" name="email" placeholder="firstname.lastname@vaimo.com" value="" required="required" class="subscribe__email" />
        <button type="submit" class="subscribe__submit">Subscribe</button>
    </fieldset>
    <p class="subscribe__state subscribe__state_in-progress">
        <span class="subscribe__spinner"></span>Subscribeing to newsletter...</p>
    <p class="subscribe__state subscribe__state_success">Subscription successful.</p>
    <p class="subscribe__state subscribe__state_fail">Email verification failed...</p>
</form>
