<!-- application/views/scripts/footer.phtml-->
<footer class="footer">
    <div class="footer__wrapper">
        <section class="footer__column">
            <h2 class="footer__title">Top Categories</h2>
            <nav class="footer__navigation"><a href="#" class="footer__link">Women</a><a href="#" class="footer__link">Men</a><a href="#" class="footer__link">Junior</a><a href="#" class="footer__link">Accessories</a></nav>
        </section>
        <section class="footer__column">
            <h2 class="footer__title">Customer Service</h2>
            <nav class="footer__navigation"><a href="#" class="footer__link">Women</a><a href="#" class="footer__link">Men</a><a href="#" class="footer__link">Junior</a><a href="#" class="footer__link">Accessories</a></nav>
        </section>
        <section class="footer__column">
            <h2 class="footer__title">Newsletter Subscribe</h2>
            <?php echo $this->render('newsletter/newsletter.phtml'); ?>
        </section>
    </div>
</footer>
