
<div class="scroller">
  <div class="scroller__wrapper">
    <figure class="scroller__slide"><img src="images/slide-1.jpg" alt="Slide" class="scroller__photo"/></figure>
    <figure class="scroller__slide"><img src="images/slide-2.jpg" alt="Slide" class="scroller__photo"/></figure>
    <figure class="scroller__slide"><img src="images/slide-3.jpg" alt="Slide" class="scroller__photo"/></figure>
    <figure class="scroller__slide"><img src="images/slide-4.jpg" alt="Slide" class="scroller__photo"/></figure>
  </div>
  <menu type="toolbar" class="scroller__menu">
    <button type="button" class="scroller__prev"></button>
    <button type="button" class="scroller__next"></button>
  </menu>
  <menu type="toolbar" class="scroller__paginator">
    <button type="button" data-page="1" class="scroller__page scroller__page_current"><span></span></button>
    <button type="button" data-page="2" class="scroller__page"><span></span></button>
    <button type="button" data-page="3" class="scroller__page"><span></span></button>
    <button type="button" data-page="4" class="scroller__page"><span></span></button>
    <button type="button" data-page="5" class="scroller__page"><span></span></button>
  </menu>
</div>