
<div class="scroller">
  <div class="scroller__wrapper">
    <div class="scroller__wrapper-inner"><a href="#" class="scroller__slide"><img src="images/slide-1.jpg" alt="Slide" class="scroller__photo"/></a><a href="#" class="scroller__slide"><img src="images/slide-2.jpg" alt="Slide" class="scroller__photo"/></a><a href="#" class="scroller__slide"><img src="images/slide-3.jpg" alt="Slide" class="scroller__photo"/></a><a href="#" class="scroller__slide"><img src="images/slide-4.jpg" alt="Slide" class="scroller__photo"/></a></div>
  </div>
  <menu type="toolbar" class="scroller__menu">
    <button type="button" class="scroller__prev"></button>
    <button type="button" class="scroller__next"></button>
  </menu>
  <menu type="toolbar" class="scroller__paginator"></menu>
</div>