
<nav class="navigation"><a href="#" class="navigation__link">Women</a><a href="#" class="navigation__link">Men</a><a href="#" class="navigation__link">Junior</a><a href="#" class="navigation__link">Accessories</a>
  <div class="navigation__dropdown"> 
    <div class="navigation__label">Collections</div>
    <div class="navigation__container">
      <div class="navigation__title">Year</div>
      <div class="navigation__dropdown"> 
        <div class="navigation__label">2014</div>
        <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
      </div>
      <div class="navigation__dropdown"> 
        <div class="navigation__label">2013</div>
        <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
      </div>
      <div class="navigation__dropdown"> 
        <div class="navigation__label">2012</div>
        <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a><a href="#" class="navigation__link">Winter</a><a href="#" class="navigation__link">Spring</a></div>
      </div>
      <div class="navigation__dropdown"> 
        <div class="navigation__label">2011</div>
        <div class="navigation__container"><a href="#" class="navigation__link">Summer</a><a href="#" class="navigation__link">Autumn</a>
          <div class="navigation__dropdown"> 
            <div class="navigation__label">Winter</div>
            <div class="navigation__container"><a href="#" class="navigation__link">First Half</a><a href="#" class="navigation__link">Second Half</a></div>
          </div><a href="#" class="navigation__link">Spring</a>
        </div>
      </div><a href="#" class="navigation__link">Link</a><a href="#" class="navigation__link">Other Link</a>
    </div>
  </div><a href="#" class="navigation__link navigation__link_marked">Sale</a><a href="#" class="navigation__link navigation__link_right">My account</a>
</nav>