
<div class="favorite">
  <h1 class="favorite__title"><span>Our Favourites</span></h1>
  <menu type="toolbar" class="favorite__menu">
    <button type="button" class="favorite__button favorite__button_prev"></button>
    <button type="button" class="favorite__button favorite__button_next"></button>
  </menu>
  <div class="favorite__wrapper-outer">
    <div class="favorite__wrapper-inner">
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Winter Sweatshirt</h2></a>
        <p class="product__price">€ 79.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Women Trousers</h2></a>
        <del class="product__price product__price_old">€ 79.00</del>
        <p class="product__price product__price_new">€ 59.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Winter Sweatshirt</h2></a>
        <p class="product__price">€ 79.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Women Trousers</h2></a>
        <del class="product__price product__price_old">€ 79.00</del>
        <p class="product__price product__price_new">€ 59.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Winter Sweatshirt</h2></a>
        <p class="product__price">€ 79.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Women Trousers</h2></a>
        <del class="product__price product__price_old">€ 79.00</del>
        <p class="product__price product__price_new">€ 59.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Winter Sweatshirt</h2></a>
        <p class="product__price">€ 79.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Women Trousers</h2></a>
        <del class="product__price product__price_old">€ 79.00</del>
        <p class="product__price product__price_new">€ 59.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Winter Sweatshirt</h2></a>
        <p class="product__price">€ 79.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Women Trousers</h2></a>
        <del class="product__price product__price_old">€ 79.00</del>
        <p class="product__price product__price_new">€ 59.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Winter Sweatshirt</h2></a>
        <p class="product__price">€ 79.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
      <article class="product"><a href="/fullview/" class="product__link">
          <figure class="product__photo-wrapper"><img src="images/product.png" alt="Product Photo" class="product__photo"/></figure>
          <h2 class="product__title">Women Trousers</h2></a>
        <del class="product__price product__price_old">€ 79.00</del>
        <p class="product__price product__price_new">€ 59.00</p>
        <nav class="product__menu"><a href="/add/item/id/" class="product__add">Add to Cart</a></nav>
      </article>
    </div>
  </div>
</div>