
<div class="card">
  <p class="card__summary">Cart 3 Items €75.00</p>
  <button type="button" class="card__checkout">Checkout</button>
  <div class="card__list">
    <div class="card__items">
      <div class="item"><a href="#" class="item__link"><img src="images/photo.jpg" alt="Item photo" class="item__photo"/>
          <div class="item__details"> 
            <h3 class="item__title">Product Name</h3>
            <p class="item__summary"> 1x € 25.00
            </p>
          </div></a>
        <button type="button" class="item__remove"></button>
      </div>
      <div class="item"><a href="#" class="item__link"><img src="images/photo.jpg" alt="Item photo" class="item__photo"/>
          <div class="item__details"> 
            <h3 class="item__title">Product Name</h3>
            <p class="item__summary"> 1x € 50.00
            </p>
          </div></a>
        <button type="button" class="item__remove"></button>
      </div>
    </div>
    <button type="button" class="card__checkout card__checkout_list">Go To Checkout</button>
  </div>
</div>